# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

draw <- function(n, p, x) {
    .Call(`_partitions_draw`, n, p, x)
}

Exp_Sampler <- function(data_, A, B, params, n_samples, spacing) {
    .Call(`_partitions_Exp_Sampler`, data_, A, B, params, n_samples, spacing)
}

Link_Sampler <- function(data_, dbindex, A, B, params, n_samples, spacing) {
    .Call(`_partitions_Link_Sampler`, data_, dbindex, A, B, params, n_samples, spacing)
}

loglikf <- function(conc, x, z, params) {
    .Call(`_partitions_loglikf`, conc, x, z, params)
}

loglikds <- function(vconc, x, z, params) {
    .Call(`_partitions_loglikds`, vconc, x, z, params)
}

loglikdsV <- function(vconc, x, z, params) {
    .Call(`_partitions_loglikdsV`, vconc, x, z, params)
}

loglikone <- function(conc, fd, x, z, params) {
    .Call(`_partitions_loglikone`, conc, fd, x, z, params)
}

loglikx <- function(x, z, params) {
    .Call(`_partitions_loglikx`, x, z, params)
}

loglikxSP <- function(betas, x, z, params) {
    .Call(`_partitions_loglikxSP`, betas, x, z, params)
}

logsumexp <- function(a, b) {
    .Call(`_partitions_logsumexp`, a, b)
}

MDM_Sampler <- function(data_, A, B, params, n_samples, spacing) {
    .Call(`_partitions_MDM_Sampler`, data_, A, B, params, n_samples, spacing)
}

a_MFM <- function(gamma, n) {
    .Call(`_partitions_a_MFM`, gamma, n)
}

b_MFM <- function(log_pK, gamma, n, upto) {
    .Call(`_partitions_b_MFM`, log_pK, gamma, n, upto)
}

unislice <- function(x0, k0, N, Khat, x1, lx, Nk, hpriorpar, w, m, lower, upper, Prior) {
    .Call(`_partitions_unislice`, x0, k0, N, Khat, x1, lx, Nk, hpriorpar, w, m, lower, upper, Prior)
}

unislicef <- function(conc, x, z, params, hpriorconc, w, m, lower, upper, x1, N, Khat, Nk, hpriorpar, Prior) {
    .Call(`_partitions_unislicef`, conc, x, z, params, hpriorconc, w, m, lower, upper, x1, N, Khat, Nk, hpriorpar, Prior)
}

unisliceds <- function(vconc, x, z, params, hpriorconc, w, m, lower, upper, x1, N, Khat, Nk, hpriorpar, Prior) {
    .Call(`_partitions_unisliceds`, vconc, x, z, params, hpriorconc, w, m, lower, upper, x1, N, Khat, Nk, hpriorpar, Prior)
}

unislicespb1 <- function(betas, x, z, params, hpriords, w, m, lower, upper, x1, N, Khat, Nk, hpriorpar, Prior) {
    .Call(`_partitions_unislicespb1`, betas, x, z, params, hpriords, w, m, lower, upper, x1, N, Khat, Nk, hpriorpar, Prior)
}

unislicespb <- function(betas, x, z, params, hpriords, w, m, lower, upper, x1, N, Khat, Nk, hpriorpar, Prior) {
    .Call(`_partitions_unislicespb`, betas, x, z, params, hpriords, w, m, lower, upper, x1, N, Khat, Nk, hpriorpar, Prior)
}

unislicem <- function(x1, N, Khat, lx, Nk, hpriorpar, w, m, lo, up, Prior, samind) {
    .Call(`_partitions_unislicem`, x1, N, Khat, lx, Nk, hpriorpar, w, m, lo, up, Prior, samind)
}

unislicemNBD <- function(x1, lx, Lm, mu0, hpriorpar, w, m, lo, up, samind) {
    .Call(`_partitions_unislicemNBD`, x1, lx, Lm, mu0, hpriorpar, w, m, lo, up, samind)
}

unislicemESCD <- function(x1, lx, Lm, mu0, hpriorpar, w, m, lo, up, samind) {
    .Call(`_partitions_unislicemESCD`, x1, lx, Lm, mu0, hpriorpar, w, m, lo, up, samind)
}

unislicem1 <- function(x1, N, Khat, lx, Nk, hpriorpar, w, m, lo, up, Prior, samind) {
    .Call(`_partitions_unislicem1`, x1, N, Khat, lx, Nk, hpriorpar, w, m, lo, up, Prior, samind)
}

unislicemGP <- function(x1, N, M, Khat, lx, Ml, hpriorpar, w, m, lo, up, samind) {
    .Call(`_partitions_unislicemGP`, x1, N, M, Khat, lx, Ml, hpriorpar, w, m, lo, up, samind)
}

Web_SamplerSP <- function(data_, assignments, A, B, distortions, params, n_samples, spacing) {
    .Call(`_partitions_Web_SamplerSP`, data_, assignments, A, B, distortions, params, n_samples, spacing)
}

Web_SamplerSP_Par <- function(data_, assignments, tclus, A, B, distortions, params, n_samples, spacing) {
    .Call(`_partitions_Web_SamplerSP_Par`, data_, assignments, tclus, A, B, distortions, params, n_samples, spacing)
}

Web_SamplerSP_Prior <- function(data_, assignments, A, B, distortions, params, n_samples, spacing) {
    .Call(`_partitions_Web_SamplerSP_Prior`, data_, assignments, A, B, distortions, params, n_samples, spacing)
}

Web_SamplerSP_Scale <- function(data_, assignments, Index, A, B, distortions, params, n_samples, spacing) {
    .Call(`_partitions_Web_SamplerSP_Scale`, data_, assignments, Index, A, B, distortions, params, n_samples, spacing)
}

Web_SamplerSP_BL <- function(data_, assignments, zblock, Idblock, A, B, distortions, params, n_samples, spacing) {
    .Call(`_partitions_Web_SamplerSP_BL`, data_, assignments, zblock, Idblock, A, B, distortions, params, n_samples, spacing)
}

Web_SamplerSP_ScaleMix <- function(data_, assignments, index, A, B, distortions, params, n_samples, spacing) {
    .Call(`_partitions_Web_SamplerSP_ScaleMix`, data_, assignments, index, A, B, distortions, params, n_samples, spacing)
}

Web_SamplerSP_ScaleBlock <- function(data_, assignments, index, A, B, distortions, params, block, mix, n_samples, spacing) {
    .Call(`_partitions_Web_SamplerSP_ScaleBlock`, data_, assignments, index, A, B, distortions, params, block, mix, n_samples, spacing)
}

